### ISSUE TITLE
Is this library alive?

### ISSUE THREAD

**Issue by soroshsabz** [iamkinetic/NEventSocket#17]
ITNOA

Hi

Is this library alive?

**Comment by danbarua** [comment]
I’m in between jobs at the moment and might take a look - I’m a bit rusty though.

**Comment by iamkinetic** [comment]
It's alive in the sense that the non-profit I work for is actively using it in some of our applications, but everything we do with the library is currently perfectly working, so I don't feel the need to put any time into it.

I'm ready to test any PR if you feel something needs to be fixed though.  And of course I would be totally fine with @danbarua doing whatever he wants with his own code! ;-)

**Comment by ajgolledge** [comment]
Do you think you will get a chance to look at #10 ?

**Comment by danbarua** [comment]
I’m going to have to go back through the history of the code because I may
have tried this before and hit an obstacle.

Can you provide some example message traffic and a use case that would
trigger it?

I suppose something in a SIP message transmitted verbatim might do it?

thanks
