### ISSUE TITLE
Support Voicemail natively

### ISSUE THREAD

**Issue by soroshsabz** [iamkinetic/NEventSocket#20]
ITNOA

**Is your feature request related to a problem? Please describe.**
This feature request is aimed at accessing the events published by freeswitch regarding it's VoiceMail functionality.

**Describe the solution you'd like**
Natively supporting Event Headers and Messages in a structured way pertaining to Voice mail module of freeswitch.

**Describe alternatives you've considered**
while these events can be manually parsed as any other custom event at a higher layer, It is preferable to Implement the parsing of these events data alongside other custom events to prevent code duplication and move logic closer to data.

**Comment by soroshsabz** [comment]
We add PR for this issue

@iamkinetic Could you please review this PR ?

Thanks

**Comment by iamkinetic** [comment]
Sorry about the delay.  Someone from my team test it and the PR is now merged.

We will release and updated nuget shortly.
