### ISSUE TITLE
Error compiling file commandlinereader

### ISSUE THREAD

**Issue by jetydu** [iamkinetic/NEventSocket#3]
'“string”未包含“To”的定义，并且找不到可接受第一个“string”类型参数的可访问扩展方法“To”(是否缺少 using 指令或程序集引用?)NEventSocket.Examples\NetCore\CommandLineReader.cs
'“PropertyInfo”未包含“GetAttribute”的定义，并且找不到可接受第一个“PropertyInfo”类型参数的可访问扩展方法“GetAttribute”(是否缺少 using 指令或程序集引用?)	NEventSocket.Examples\NetCore\CommandLineReader.cs

命名空间“Net”中不存在类型或命名空间名“System”(是否缺少程序集引用?)	NEventSocket.Examples	K:\FSEventSocket\NEventSocket.Examples\NetCore\CommandLineReader.cs
命名空间“Net”中不存在类型或命名空间名“Text”(是否缺少程序集引用?)	NEventSocket.Examples	K:\FSEventSocket\NEventSocket.Examples\NetCore\CommandLineReader.cs

**Comment by iamkinetic** [comment]
I'm sorry, i can't read this language! :-(
