### ISSUE TITLE
Value cannot be null. (Parameter 'factory')

### ISSUE THREAD

**Issue by panicou** [iamkinetic/NEventSocket#5]
I created a simple program and got Value cannot be null. (Parameter 'factory') from Microsoft.Extensions.Logging.Abstractions

code as follows : 

using System;
using System.Reactive.Linq;
using System.Threading.Tasks;
using NEventSocket;
using NEventSocket.FreeSwitch;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await CallTracking();

            Console.WriteLine("Hello World!");
        }

        public static async Task CallTracking()
        {
            using (var socket = await InboundSocket.Connect("XXX.XXX.XXX.XXX", 8021, "ClueCon"))
            {
                var apiResponse = await socket.SendApi("status");
                Console.WriteLine(apiResponse.BodyText);

                //Tell FreeSwitch which events we are interested in
                await socket.SubscribeEvents(EventName.ChannelAnswer);

                //Handle events as they come in using Rx
                socket.ChannelEvents.Where(x => x.EventName == EventName.ChannelAnswer)
                      .Subscribe(async x =>
                      {
                          Console.WriteLine("Channel Answer Event " + x.UUID);

                          //we have a channel id, now we can control it
                          await socket.Play(x.UUID, "misc/8000/misc-freeswitch_is_state_of_the_art.wav");
                      });
            }
        }
    }
}

any ideas ??

i am using .net core 3.1

**Comment by lilunxm12** [comment]
Add `NEventSocket.Logging.Logger.Configure(new LoggerFactory());` before your initialize any NEventSocket class

**Comment by panicou** [comment]
thx that solved it.

**Comment by samuelting** [comment]
This error message reminds you of specifying loggers used by NEventSocket Library. If you want to log NEventSocket with your logger, you may need to consider adding this in `ConfigureServices` method in the `StartUp.cs` in your .NET core application.

```
NEventSocket.Logging.Logger.Configure(LoggerFactory.Create(builder => {
                builder
                .AddConsole();
            }));
```
